'(label rev (lambda (s) 
    ((lambda (append)
        (cond ((eq s '()) "")
          ('t (+ (rev (cdr s)) (car s)))
        )
     )
     '(lambda (x y)
         (cond ((eq x '()) y)
               ('t (cons (car x) (append (cdr x) y)))
         )
      )
    )
 ))
